### ISSUE TITLE
应用崩溃了，模块启用后系统应用无法使用

### ISSUE THREAD

**Issue by ckl159753** [jrsen/Xposed-GodMode#2]
java.lang.RuntimeException: Unable to create service com.android.providers.downloads.service.DownloadService: java.lang.RuntimeException: Unable to create application com.android.providers.downloads.DownloadApplication: java.lang.IllegalArgumentException: Expected receiver of type android.view.View, but got android.app.Instrumentation
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3085)
	at android.app.ActivityThread.access$2000(ActivityThread.java:180)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1591)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5837)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.RuntimeException: Unable to create application com.android.providers.downloads.DownloadApplication: java.lang.IllegalArgumentException: Expected receiver of type android.view.View, but got android.app.Instrumentation
	at android.app.LoadedApk.makeApplication(LoadedApk.java:606)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3072)
	... 9 more
Caused by: java.lang.IllegalArgumentException: Expected receiver of type android.view.View, but got android.app.Instrumentation
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.view.View.<init>(<Xposed>)
	at com.miui.internal.variable.v21.Android_View_View_class.handle_init_(SourceFile:41)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:603)
	... 10 more

**Comment by jrsen** [comment]
该问题2.7.7版本已修复
