### ISSUE TITLE
最新版本无法正常运行

### ISSUE THREAD

**Issue by n0vacula** [jrsen/Xposed-GodMode#5]
java.lang.RuntimeException: Unable to resume activity {com.viewblocker.jrsen/com.viewblocker.jrsen.SettingsActivity}: com.a.a.r: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 286 path $.[0].j
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3726)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3766)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2995)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6753)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
Caused by: com.a.a.r: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 286 path $.[0].j
	at com.a.a.b.a.i$a.b(Unknown Source:53)
	at com.a.a.b.a.m.b(Unknown Source:2)
	at com.a.a.b.a.b$a.a(Unknown Source:32)
	at com.a.a.b.a.b$a.b(Unknown Source:0)
	at com.a.a.b.a.m.b(Unknown Source:2)
	at com.a.a.b.a.g$a.a(Unknown Source:110)
	at com.a.a.b.a.g$a.b(Unknown Source:0)
	at com.a.a.e.a(Unknown Source:20)
	at com.a.a.e.a(Unknown Source:4)
	at com.a.a.e.a(Unknown Source:9)
	at com.a.a.e.a(Unknown Source:0)
	at com.viewblocker.jrsen.service.a.a(Unknown Source:19)
	at com.viewblocker.jrsen.service.a.d(Unknown Source:40)
	at com.viewblocker.jrsen.c.b.a(Unknown Source:27)
	at com.viewblocker.jrsen.c.b.onResume(Unknown Source:13)
	at android.app.Fragment.performResume(Fragment.java:2554)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1322)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3027)
	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2989)
	at android.app.FragmentController.dispatchResume(FragmentController.java:200)
	at android.app.Activity.performResume(Activity.java:7165)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3700)
	... 11 more
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 286 path $.[0].j
	at com.a.a.d.a.h(Unknown Source:131)
	at com.a.a.b.a.n$8.a(Unknown Source:26)
	at com.a.a.b.a.n$8.b(Unknown Source:0)
	at com.a.a.b.a.i$1.a(Unknown Source:2)
	at com.a.a.b.a.i$a.b(Unknown Source:57)
	... 34 more

**Comment by jrsen** [comment]
因为ProGuard导致 2.7.7新版本已解决该问题
