### ISSUE TITLE
SONY Xperia XZ1 启用后无限FC手机崩溃

### ISSUE THREAD

**Issue by ZeroSimple** [jrsen/Xposed-GodMode#6]
激活此模块后，手机重启即FC，且无法启动任何应用，包括设置

**Comment by jrsen** [comment]
麻烦提供相应的崩溃日志 谢谢

**Comment by yaohunzhanyue** [comment]
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 10034404 bytes
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:125)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.content.ClipboardManager.setPrimaryClip(<Xposed>)
	at com.viewblocker.jrsen.util.a.a(Unknown Source)
	at com.viewblocker.jrsen.SettingsActivity$1.onClick(Unknown Source)
	at android.support.v7.app.AlertController$b.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6365)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: android.os.TransactionTooLargeException: data parcel size 10034404 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:618)
	at android.content.IClipboard$Stub$Proxy.setPrimaryClip(IClipboard.java:170)
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:123)
	... 13 more

**Comment by jrsen** [comment]
新版本2.7.7已解决
