### ISSUE TITLE
打开主界面无限崩溃

### ISSUE THREAD

**Issue by AkiraLan** [jrsen/Xposed-GodMode#7]
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 10251700 bytes
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:132)
	at com.viewblocker.jrsen.util.a.a(Unknown Source)
	at com.viewblocker.jrsen.SettingsActivity$1.onClick(Unknown Source)
	at android.support.v7.app.AlertController$b.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6259)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:803)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
Caused by: android.os.TransactionTooLargeException: data parcel size 10251700 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:618)
	at android.content.IClipboard$Stub$Proxy.setPrimaryClip(IClipboard.java:170)
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:130)
	... 10 more

**Comment by jrsen** [comment]
fixed
