### ISSUE TITLE
我也不知道什么问题，突然就提示这个，但是可以正常使用

### ISSUE THREAD

**Issue by aslarn** [jrsen/Xposed-GodMode#9]
java.lang.RuntimeException: Unable to bind to service com.android.settings.development.qstile.DevelopmentTiles$ShowLayout@fe5937b with Intent { cmp=com.android.settings/.development.qstile.DevelopmentTiles$ShowLayout (has extras) }: java.lang.SecurityException: Component outside caller's uid
	at android.app.ActivityThread.handleBindService(ActivityThread.java:3615)
	at android.app.ActivityThread.access$1400(ActivityThread.java:202)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1679)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6740)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
Caused by: java.lang.SecurityException: Component outside caller's uid
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.service.quicksettings.IQSService$Stub$Proxy.getTile(IQSService.java:190)
	at android.service.quicksettings.TileService.onBind(TileService.java:331)
	at android.app.ActivityThread.handleBindService(ActivityThread.java:3599)
	... 8 more

**Comment by jrsen** [comment]
这个问题貌似不是上帝模式引起的
